version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: warandpeace-bot
    command: python3 src/bot.py
    env_file:
      - .env
    volumes:
      - ./database:/app/database
    restart: unless-stopped
