version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: warandpeace-bot
    command: python3 src/bot.py
    env_file:
      - .env
    environment:
      - METRICS_ENABLED=${METRICS_ENABLED:-true}
      - METRICS_PORT=${METRICS_PORT:-8000}
    volumes:
      - ./database:/app/database
    ports:
      - "${METRICS_PORT:-8000}:8000"
    restart: unless-stopped
